### PR TITLE
Fixed getting Boolean values in properties 

### LINKED ISSUE #95: Consider using Properties#get when building filter
https://github.com/hazelcast/hazelcast-wm/blob/d71ea59a3642ea1a4e28e39206be4bd703a6ea7d/src/main/java/com/hazelcast/web/WebFilterConfig.java#L371

might cause some properties to be ignored during programmatic configuration (i.e. as Spring bean). For instance,
```
Properties properties = new Properties();
properties.put("cookie-http-only", true);
new WebFilter(properties);
```
will create a wilter where `cookie-http-only = false`.

### PR DESCRIPTION
**Pull request by OmarMorales71**
Method getValue try to get a property with a string value (getProperty()). 
When you try to get a Boolean property, this method return a null (because it just can get String values) 
and that's the reason the app put the default value to that property.

I fixed it using the get() method instead getProperty(). get() return an Object and after that I cast it to the type of value I need (in this case Boolean).

Check List:

Fixes #95 
Unit tests : YES

### CODE REVIEW

**Comment by enozcan** [comment]
Thanks for the PR @OmarMorales71!
I will work through WebFilterConfig and review asap.

**Comment by enozcan** [comment]
verify

File: src/test/java/com/hazelcast/wm/test/WebFilterConfigTest.java [hunk 1]
```diff
@@ -88,4 +88,12 @@ public void propertiesOverrideServletFilterConfiguration() throws Exception {
...
         Assert.assertEquals("cookie1", webFilterConfig.getCookieName());
     }
+
+    @Test
+    public void testBooleanConfigValue() {
+        Properties properties = new Properties();
+        properties.put(WebFilterConfig.COOKIE_HTTP_ONLY, true);
+        WebFilterConfig config = WebFilterConfig.create(emptyFilterConfig, properties);
+        Assert.assertEquals(true, config.isCookieHttpOnly());
+    }
```
Comment (enozcan) [inline src/test/java/com/hazelcast/wm/test/WebFilterConfigTest.java:98]: Let's not limit this test's coverage with boolean values.
```suggestion
    public void testNonStringConfigValues() {
        Properties properties = new Properties();
        properties.put(WebFilterConfig.COOKIE_HTTP_ONLY, true);
        properties.put(WebFilterConfig.COOKIE_MAX_AGE, 160);
        WebFilterConfig config = WebFilterConfig.create(emptyFilterConfig, properties);
        Assert.assertEquals(true, config.isCookieHttpOnly());
        Assert.assertEquals(160, config.getCookieMaxAge());
    }
```

**Review by enozcan — CHANGES_REQUESTED** [review]

**Comment by OmarMorales71** [comment]
@enozcan I have fixed what you asked for. I checked that my solution works with boolean, int, double, etc. (not just boolean).

**Comment by enozcan** [comment]
verify

**Review by enozcan — APPROVED** [review]

File: src/main/java/com/hazelcast/web/WebFilterConfig.java [hunk 2]
```diff
@@ -368,7 +368,8 @@ private static URL getConfigUrl(final ServletContext ctx, final String configLoc
 
     private static String getValue(FilterConfig filterConfig, Properties properties, String paramName) {
         if (properties != null && properties.containsKey(paramName)) {
-            return properties.getProperty(paramName);
+            Object property = properties.get(paramName);
+            return property == null ? filterConfig.getInitParameter(paramName) : property.toString();
```
Comment (alparslanavci) [inline src/main/java/com/hazelcast/web/WebFilterConfig.java:372]: Is it ok to update this method as follows?

```
    private static String getValue(FilterConfig filterConfig, Properties properties, String paramName) {
        if (properties != null && properties.containsKey(paramName)) {
            Object property = properties.get(paramName);
            if (property != null) {
                return property.toString();
            }
        }
        return filterConfig.getInitParameter(paramName);
    }
```

**Review by alparslanavci — APPROVED** [review]
A small refactoring, otherwise LGTM 👍

**Comment by enozcan** [comment]
verify

**Comment by enozcan** [comment]
Thanks for the PR @OmarMorales71!
